name: "Trigger: on Push/PR"


on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - 'setup.cfg'
      - '**/*.py'
      - '**/*.pyi'
      - '.github/workflows/run_bandit.yml'
      - '.github/workflows/run_tests.yml'
      - '!docs/**'
      - '!examples/**'
      - '!tools/**'

  pull_request:
    paths:
      - 'setup.cfg'
      - '**/*.py'
      - '**/*.pyi'
      - '.github/workflows/run_bandit.yml'
      - '.github/workflows/run_tests.yml'
      - '!docs/**'
      - '!examples/**'
      - '!tools/**'

jobs:
  run-bandit:
    permissions:
      security-events: write

    uses: ./.github/workflows/run_bandit.yml

  run-tests:
    uses: ./.github/workflows/run_tests.yml


# The end.
